# Generated by Django 4.2.4 on 2023-10-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('question', models.CharField(max_length=10000)),
                ('choice1', models.CharField(max_length=1000)),
                ('choice2', models.CharField(max_length=1000)),
                ('choice3', models.CharField(max_length=1000)),
                ('choice4', models.CharField(max_length=1000)),
                ('correctans', models.CharField(max_length=1000)),
            ],
        ),
    ]
