# Generated by Django 4.2.4 on 2023-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cquiz', '0002_alter_questions_choice1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='choice1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=10000),
        ),
    ]
