# Generated by Django 4.2.4 on 2023-10-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cquiz', '0003_alter_questions_choice1_alter_questions_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='correctans',
            new_name='anschoiceno',
        ),
    ]
