# Generated by Django 4.2.4 on 2023-10-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cquiz', '0004_rename_correctans_questions_anschoiceno'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('RegisterNo', models.CharField(max_length=20)),
            ],
        ),
    ]
